### ISSUE TITLE
Add Feature: parse already fetched html instead of fetching it self

### ISSUE THREAD

**Issue by peanutbother** [mem0master/openGraphParser#1]
The title already says it all but I may clarify it.

I would like to use this library for OGP parsing of html documents I create / alter / already fetched.
For this case I don't want openGraphParser to fetch the document but instead parse the document.

Your code already has the feature but you are only exposing the `extractMeta` method.
I will send a pull request for that

**Comment by mem0master** [comment]
Sorry for the late response, it was on a secondary account (I totally forgot i had that one)

Thanks
